### ISSUE TITLE
prometheus-operatorのHelmチャートはcoreosからstableに移動されているようです

### ISSUE THREAD

**Issue by ryotan** [RoboticBase/core#2]
[coreos/prometheus-operator](https://github.com/coreos/prometheus-operator) のHelmチャートは既にDeprecatedになってHelmのstableに移動されているようなので、 [stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) を利用するようにしていただきたいです。

https://github.com/coreos/prometheus-operator/blob/master/helm/README.md

> The helm charts originally developed as part of this repository have been moved to stable/prometheus-operator.

READMEを確認した限りでは、 coreos/kube-prometheus とほぼ同じコンポーネントがインストールされるようですが、Prometheusのルールなどの違いは確認していません。

これから新規に利用する場合は、 stable/prometheus-operator を利用するほうが良いと思うので、検討をお願いします。

**Comment by nmatsui** [comment]
ありがとうございます。
stable/prometheus-operatorの実装を確認し、次回のリリース時に対応します。

**Comment by nmatsui** [comment]
Release 0.4.3 で対応しました。
